FROM debian:bookworm-slim

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  rsync && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN useradd hl -u 10001 --create-home --user-group
USER 10001
WORKDIR /home/hl/apps
ENV PATH="/home/hl/.local/bin:${PATH}"




