name: Docker Build and Push
on:
  workflow_call:
    inputs:
      registry:
        description: Docker registry
        required: true
        type: string
      image-name:
        description: Image name
        required: true
        type: string
      file:
        description: Dockerfile
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image-name }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ${{ inputs.file }}
          tags: ${{ steps.meta.outputs.tags }}, ${{ inputs.registry }}/${{ inputs.image-name }}:${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
