name: Cleanup old packages

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  
jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - homelab-provisioner-toolbox-rsync
          - homelab-provisioner-toolbox

    steps:
      - name: Cleanup packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package }}
          package-type: container
          min-versions-to-keep: 5
