name: Build provisioner toolbox image
on:
  workflow_dispatch:
  push:
    paths:
      - "Containerfile"
      - "requirements.txt"
      - "apps/**"

jobs:
  provisioner-toolbox-build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-push.yml
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}
      file: ./Containerfile
