name: Build rsync image
on:
  workflow_dispatch:
  push:
    paths:
      - "Containerfile_rsync"

jobs:
  rsync-build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-push.yml
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}-rsync
      file: ./Containerfile_rsync
